
name: dbt_snowflake_demo
version: 1.0.0
config-version: 2

profile: snowflake_demo_profile

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
    - "dbt_modules"

seeds:
  +quote_columns: false

models:
  dbt_snowflake_demo:
      marts:
        core:
          +materialized: table
