
name: dbt_snowflake_demo
version: 1.0.0
config-version: 2

profile: snowflake_demo_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
    - "dbt_modules"

dispatch:
  - macro_namespace: dbt
    search_order:
      - dbt_snowflake_demo
      - dbt_snowflake_monitoring
      - dbt

query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true

seeds:
  +quote_columns: false

models:
  dbt_snowflake_demo:
      marts:
        core:
          +materialized: table
  dbt_snowflake_monitoring:
    +schema: _package_dbt_snowflake_monitoring
